### ISSUE TITLE
please release latest version to rubygems

### ISSUE THREAD

**Issue by gnowxilef** [pewniak747/hipbot#17]
i don't think the 1.0.3 version has been bumped since january of 2014?

**Comment by gnowxilef** [comment]
poke?

**Comment by gnowxilef** [comment]
poke again?

**Comment by bartoszkopinski** [comment]
@gnowxilef Done but this gem is no longer maintained as none of us uses Hipchat anymore.
https://rubygems.org/gems/hipbot/versions/1.0.4
