### ISSUE TITLE
Send message at specific time

### ISSUE THREAD

**Issue by hevamb** [pewniak747/hipbot#18]
Hello, 

I'd like to be able to send a message at a specific time rather than wait for a response

e.g. 

 at '9am' do 
 reply("Good Morning Everyone!")
 end

Is this possible?

**Comment by bartoszkopinski** [comment]
@hevamb This is not implemented, only timers are available using eventmachine. You'd have to use something like https://github.com/jmettraux/rufus-scheduler or https://github.com/tomykaira/clockwork or https://github.com/plashchynski/crono

**Comment by hevamb** [comment]
Thanks, I'll look into that :)
